# Generated by Django 3.2 on 2021-04-14 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='d_endhours',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='patients',
            name='p_gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='patients',
            name='p_history',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='d_starthours',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
