# Generated by Django 3.2 on 2021-04-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0004_auto_20210415_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='d_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='doctors',
            name='d_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
