# Generated by Django 3.2 on 2021-04-13 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='d_starthours',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctors',
            name='d_yoe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='p_dob',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='patients',
            name='p_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
